# Generated by Django 4.2.5 on 2023-09-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petproassist', '0003_remove_animal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='animals',
            field=models.ManyToManyField(blank=True, to='petproassist.animal'),
        ),
    ]
