# Generated by Django 4.2.5 on 2023-09-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petproassist', '0004_customuser_animals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='animals',
            field=models.ManyToManyField(choices=[('chien', 'Chien'), ('chat', 'Chat'), ('poule', 'Poule'), ('oiseau', 'Oiseau'), ('lapin', 'Lapin'), ('poisson', 'Poisson'), ('autre', 'Autre')], to='petproassist.animal'),
        ),
    ]
