# Generated by Django 4.2.5 on 2023-09-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petproassist', '0005_alter_customuser_animals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='animals',
            field=models.ManyToManyField(blank=True, to='petproassist.animal'),
        ),
    ]
