# Generated by Django 4.2.5 on 2023-09-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petproassist', '0006_alter_customuser_animals'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tel',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
