# Generated by Django 4.2.5 on 2023-09-15 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petproassist', '0010_remove_publication_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_presta',
            new_name='is_owner',
        ),
    ]
